07/04/21 (23:30:27) | ERROR: Exception when sending signal 9 to pid 759
07/04/21 (23:30:27) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5432, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
07/04/21 (23:30:37) | ERROR: Exception when sending signal 9 to pid 759
07/04/21 (23:30:37) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5432, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
07/04/21 (23:30:38) | ERROR: Exception when sending signal 9 to pid 759
07/04/21 (23:30:38) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5432, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
07/04/21 (23:30:39) | ERROR: Exception when sending signal 9 to pid 759
07/04/21 (23:30:39) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5432, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
